[behavior]
edit_after_power_off = true
sleep_after_upload = false

[capture_device]
name = "Capture Device"

[obs]
websocket_host = "localhost"
websocket_port = 4455
websocket_password = ""
executable_path = "C:\\Program Files\\obs-studio\\bin\\64bit\\obs64.exe"

[record]
capture_index = 0

[speech_transcriber]
mic_device_name = "マイク (USB Audio Device)"
groq_api_key = ""
groq_model = "whisper-large-v3"
integrator_model = "openai/gpt-oss-120b"
language = "ja-JP"
phrase_time_limit = 3.0
custom_dictionary = ["ナイス", "キル", "デス"]
vad_aggressiveness = 2

[video_storage]
base_dir = "videos"

[video_edit]
volume_multiplier = 1.0
title_template = "{BATTLE}({RATE}) {RULE} {WIN}勝{LOSE}敗 {DAY:'%y.%m.%d} {SCHEDULE:%H}時～"
description_template = "{CHAPTERS}"
chapter_template = "{RESULT:<5} {KILL:>3}k {DEATH:>3}d {SPECIAL:>3}s  {STAGE}"

[upload]
privacy_status = "private"
tags = ["Splatoon3"]
playlist_id = ""
caption_name = "ひとりごと"
